### PR TITLE
add health endpoint

### PR DESCRIPTION
**Pull request by macmoritz**
Added an health endpoint which returns ok.

### CODE REVIEW

**Comment by EpicWink** [comment]
I would prefer to return JSON in endpoints not meant for users (eg `{"status": "success", "data": None}`, with JSON content-type header). Do you specifically need the body to be `OK`?

**Comment by macmoritz** [comment]
No, JSON is totally fine. Feel free to change an merge!

**Comment by macmoritz** [comment]
I changed to JSON and also added a test for the health endpoint, better save than sorry.

**Comment by doc-sheet** [comment]
Would you mind adding `/ready` endpoint which indicates if cache is filled?

**Pull request merged**
