### PR TITLE
chore: added multiarch support for docker builder 🐳

### PR DESCRIPTION
**Pull request by Christian-TD**
Adding multi-arch support for building docker image. Give it a try!

### CODE REVIEW

**Comment by EpicWink** [comment]
I need to do more investigation here, like whether `xx` it's required, or how easy it is to maintain the new platforms (for instance, running the test suite after building the images).

**Comment by Christian-TD** [comment]
> I need to do more investigation here, like whether `xx` it's required, or how easy it is to maintain the new platforms (for instance, running the test suite after building the images).

Sure, no problem. Here's the link to [xx](https://github.com/tonistiigi/xx)

**Comment by EpicWink** [comment]
Does #45 meet your needs?

**Comment by Christian-TD** [comment]
> Does #45 meet your needs?

Yep, that's looks perfectly fine. Great job, thanks!

**Comment by EpicWink** [comment]
Closing as superceded, feel free to comment if you want `xx`-based Docker images

**Pull request closed without merging**
